/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_ele_amigo_utils_SymbolicLinkUtil */

#ifndef _Included_me_ele_amigo_utils_SymbolicLinkUtil
#define _Included_me_ele_amigo_utils_SymbolicLinkUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_ele_amigo_utils_SymbolicLinkUtil
 * Method:    makeSymbolicLink
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jint JNICALL Java_me_ele_amigo_utils_SymbolicLinkUtil_makeSymbolicLink
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif



